Claire branch
JesseDenier/Recipe-Creator pull request #11
Opened 2024-02-03 18:30 UTC by cshipley98

added styling

2024-02-03 18:42 UTC, eimonto22 approved these changes
looks good

2024-02-05 16:16 UTC, JesseDenier requested changes
I may be mistaken but on a quick glance this doesn't seem to use Foundation?

2024-02-06 00:41 UTC, eimonto22 approved these changes

2024-02-06 00:42 UTC, JesseDenier approved these changes

2024-02-06 00:42 UTC, merged